name: Lab5 ETL Pipeline CI/CD

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

env:
  AWS_REGION: eu-north-1
  STEP_FUNCTION_NAME: lab5-lakehouse-stepfunc

jobs:
  # Job 1: CI for Spark Jobs
  spark-ci:
    name: Spark Job CI
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Cache pip dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
          
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyspark==3.4.0
        pip install pytest pytest-cov
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        
    - name: Lint Spark Jobs
      run: |
        pip install flake8
        # Stop build if there are Python syntax errors or undefined names
        flake8 spark-jobs/ --count --select=E9,F63,F7,F82 --show-source --statistics
        # Exit-zero treats all errors as warnings
        flake8 spark-jobs/ --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
        
    - name: Run Spark Job Tests
      run: |
        # Run unit tests for Spark jobs
        if [ -d "tests/" ]; then
          python -m pytest tests/ -v --cov=spark-jobs --cov-report=xml
        else
          echo "No tests directory found, skipping tests"
        fi
        
    - name: Validate Spark Job Syntax
      run: |
        # Check if Spark jobs can be imported without syntax errors
        for file in spark-jobs/*.py; do
          if [ -f "$file" ]; then
            echo "Validating $file"
            python -m py_compile "$file"
          fi
        done
        
    - name: Upload coverage reports
      if: success()
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage.xml
        fail_ci_if_error: false
